export const prompts = [
  "Mondays are now cancelled due to ___.",
  "The year is 2077 and CD PROJEKT RED released their new game called ___.",
  "Japan's birthrate is skyrocketing thanks to ___.",
  "Describe an emoji for when you are in a gamer mood.",
  "Donald Trump's slogan for re-election.",
  "A weird side effect from the Covid-19 vaccine.",
  "What would the USA rather do than give Puerto Rico independence?",
  "___, fun for the whole family.",
  "Schools are now forced to teach about ___ in class.",
  "Your girlfriend sends you a text saying 'I'm breaking up with you' what does it mean?",
  "No Nut November is almost over, however, ___ walks in and you immediately lose.",
  "A twitter post J.K Rowling didn't mean to send.",
  "Quickest way to get expelled?",
  "What kind of surgery would you pay 100,000 USD in order to get?",
  "___  -- the top sign your partner is cheating on you.",
  "For a limited time only, you can buy ___ at your local game stop.",
];
